### ISSUE TITLE
CSS-merge и font-face

### ISSUE THREAD

**Issue by lifecom** [livestreet/livestreet#673]
**Оригинал:**
```css
@font-face {
    font-family: 'Glyphicons Halflings';
    src: url('../fonts/glyphicons-halflings-regular.eot');
    src: url('../fonts/glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
         url('../fonts/glyphicons-halflings-regular.woff') format('woff'),
         url('../fonts/glyphicons-halflings-regular.ttf') format('truetype'),
         url('../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```
**Смержено** (для наглядности де-минифицировано):
```css
@font-face {
    font-family: "Glyphicons Halflings";
    src: url("../fonts/glyphicons-halflings-regular.eot?#iefix") format("embedded-opentype"),
         url("../fonts/glyphicons-halflings-regular.woff") format("woff"),
         url("../fonts/glyphicons-halflings-regular.ttf") format("truetype"),
         url("") format("svg");
}
```
**Что "поломалось":**
* ~~Исчезло верхнее свойство *src* (вероятно, забирается **последнее** из повторяющихся)~~
* Исчезла ссылка на *svg* (вероятно, из-за приставки *#glyphicons_halflingsregular*)
